### ISSUE TITLE
[无法搜索] 

### ISSUE THREAD

**Issue by mingyue0094** [Hk-Gosuto/ChatGPT-Next-Web#25]
#  曲线的解决了 
> https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/issues/25#issuecomment-1728727826

----
~~# 原因如下~~

~~### 仅 openapi 官方原版接口可用这个搜索。~~

~~https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/issues/19#issuecomment-1722724521~~

-------

ddg api 搭建成功的。
# ddg api部分
访问：http://192.168.10.20:8081/search?q=啊对对对是什么梗&max_results=3
正常json 格式的返回结果。

# ChatGPT-Next-Web-LangChain 部分
git reset --hard 933d4c3a961cc8981aeb7bc514e529b90cacf9ca 
>  https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/tree/v2.9.6 版本的。

docke 构建镜像
镜像启动参数
-e WEB_SEARCH_BASE_URL="http://192.168.10.20:8081"

# 容器启动后。

和没接入联网插件一样。
```
## 来自你的消息:
搜索2023年马斯克

## 来自 ChatGPT 的消息:
很抱歉，我无法进行实时搜索或提供最新的信息，因为我的知识截止日期是2021年9月，而我无法浏览互联网。如果您想了解关于2023年的埃隆·马斯克（Elon Musk）的信息，我建议您访问新闻网站、社交媒体或搜索引擎，以获取最新的新闻和事件。马斯克是特斯拉和SpaceX的创始人，他在科技和太空探索领域有许多活动，因此可以在各种新闻来源中找到相关信息。
```

# 其他
- 第一次用最新版本构建的镜像，启动后无法用搜索。 然后改用 tag:v2.9.6 的仍然用不了。

**Comment by Hk-Gosuto** [comment]
新版本已经不需要单独部署 ddg 的查询接口了，`WEB_SEARCH_BASE_URL` 这个环境变量也没了。
详细参考首页 README 中的说明

**Comment by Hk-Gosuto** [comment]
ddg 搜索目前无法单独配置代理，建议参考 [环境变量](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain?tab=readme-ov-file#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F) 配置 `SERPAPI_API_KEY ` 或 `BING_SEARCH_API_KEY ` 这两个服务目前在国内是可以正常使用的。

如果仍无法使用请检查以下几个位置的插件开关是否开启：
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/45858f93-e468-46bb-950e-05d74b46d97f)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/a52adf61-53c7-4505-80af-085d0a9987d3)
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/4395d539-cf3f-49ed-9802-0b9df48284f5)

正常的效果是这样的：
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/14031260/155bcf51-3e22-4154-a870-3e9c3493fbf3)

**Comment by Hk-Gosuto** [comment]
上面插件图标全黑的时候即为开启。
你使用的是什么模型？调用的是否是 openai 官方的 api 接口？

**Comment by Hk-Gosuto** [comment]
> > 上面插件图标全黑的时候即为开启。 你使用的是什么模型？调用的是否是 openai 官方的 api 接口？
> 
> chatgpt 网页token 的方式。 `-e OPENAI_API_KEY=xxx ` 请求的是 golang版本的‘网页版官网反代’ 接口。
> 
> `本地浏览器` ---- `ChatGPT-Next-Web-LangChain` --- `chatgpt伪官网` --- `chatgpt官网`
> 
> 本地浏览器
> 
> > 任意模型，因为后端不判断这个模型，直接请求gpt官网的 `text-davinci-002-render-sha`

如果想使用以前那种基于上下文的模式来进行搜索的话这个是最后一个使用该方式的版本：
https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/releases/tag/v2.9.1
