### ISSUE TITLE
[Feature] 请问您可以做一个docker image么

### ISSUE THREAD

**Issue by wangshaoce** [Hk-Gosuto/ChatGPT-Next-Web#3]
我希望使用您fork的 支持联网搜索的功能。 您可以将您fork的项目 打包成docker image么？

**Comment by Hk-Gosuto** [comment]
> 我希望使用您fork的 支持联网搜索的功能。 您可以将您fork的项目 打包成docker image么？

使用这个镜像 `gosuto/chatgpt-next-web`
