### ISSUE TITLE
Failed to get the VQD for query "X"

### ISSUE THREAD

**Issue by FrostMiKu** [Hk-Gosuto/ChatGPT-Next-Web#4]
**描述问题**
启用联网查找后出现 `Failed to get the VQD for query "啊对对对对"` 错误
Snazzah/duck-duck-scrape/issues/119 
有过相关BUG报告，但似乎已经修复，我检查过package.json 确实也是 2.2.4以上，但仍存在该问题。

**如何复现**
启用联网查找

**截图**
```
chat-chat-1  | [Tools]  Error: Failed to get the VQD for query "jobs是谁？".
chat-chat-1  |     at getVQD (/app/.next/server/chunks/2180.js:1159:15)
chat-chat-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
chat-chat-1  |     at async search (/app/.next/server/chunks/2180.js:325:21)
chat-chat-1  |     at async handle (/app/.next/server/app/api/tools/ddg/route.js:350:31)
chat-chat-1  |     at async /app/.next/server/chunks/2180.js:16459:37
```

**一些必要的信息**
 - 版本：main分支
 - 部署方式：docker

**Comment by Hk-Gosuto** [comment]
> **描述问题** 启用联网查找后出现 `Failed to get the VQD for query "啊对对对对"` 错误 [Snazzah/duck-duck-scrape/issues/119](https://github.com/Snazzah/duck-duck-scrape/issues/119) 有过相关BUG报告，但似乎已经修复，我检查过package.json 确实也是 2.2.4以上，但仍存在该问题。
> 
> **如何复现** 启用联网查找
> 
> **截图**
> 
> ```
> chat-chat-1  | [Tools]  Error: Failed to get the VQD for query "jobs是谁？".
> chat-chat-1  |     at getVQD (/app/.next/server/chunks/2180.js:1159:15)
> chat-chat-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> chat-chat-1  |     at async search (/app/.next/server/chunks/2180.js:325:21)
> chat-chat-1  |     at async handle (/app/.next/server/app/api/tools/ddg/route.js:350:31)
> chat-chat-1  |     at async /app/.next/server/chunks/2180.js:16459:37
> ```
> 
> **一些必要的信息**
> 
> * 版本：main分支
> * 部署方式：docker

试了一下当前的最新镜像，并没有复现该问题。
有可能是网络问题导致，请尝试配置代理 `PROXY_URL`。
```shell
docker run --rm -it -p 3000:3000 -e OPENAI_API_KEY="sk-xxxx" -e PROXY_URL="http://127.0.0.1:7890" gosuto/chatgpt-next-web
```
