### ISSUE TITLE
[Bug] 无法自动更新

### ISSUE THREAD

**Issue by xxj7527** [Hk-Gosuto/ChatGPT-Next-Web#64]
只有第一次可以是不是文件没同步修改手动也不行
![image](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/86597262/474153b5-b0d1-4721-835b-2add353163a1)

**Comment by Hk-Gosuto** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/issues/872

**Comment by Hk-Gosuto** [comment]
手动同步一次，后面再试试能不能自动同步
